# action.yml
name: 'Build Rust'
description: 'Build Rust'
inputs:
  context:
    description: 'Path to the lambda function'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/cogup/actions/lambda-rust:main'
  args:
    - ${{ inputs.context }}