name: 'Devops Definitions Image'
description: 'Update coggpt image in devops repo'
inputs:
  name:
    description: 'Repository name'
    required: true
  tag:
    description: 'Image tag to update in coggpt.ts'
    required: true
  token:
    description: 'GitHub token'
    required: true
  definition:
    description: 'Path to the definition file. .ts, .json, .yml or .yaml files are supported'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout devops repo
      uses: actions/checkout@v4
      with:
        repository: cogup/devops
        ref: main
        token: ${{ inputs.token }}
        path: devops

    - name: Modify coggpt.ts with new image tag
      shell: bash
      run: |
        sed -i "s|458905170631.dkr.ecr.us-east-1.amazonaws.com/coggpt:.*|458905170631.dkr.ecr.us-east-1.amazonaws.com/coggpt:${{ inputs.tag }}\",|" devops/cdk-services/definitions/${{ inputs.definition }}

    - name: Commit and push changes
      shell: bash
      run: |
        cd devops
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b ${{ inputs.name }}-update-definition-image-${{ inputs.tag }}
        git add cdk-services/definitions/${{ inputs.definition }}
        git commit -m "Update ${{ inputs.name }} image with tag ${{ inputs.tag }}"
        git push origin ${{ inputs.name }}-update-definition-image-${{ inputs.tag }}

    - name: Install GitHub CLI
      shell: bash
      run: sudo apt-get install -y gh

    - name: Create Pull Request with GitHub CLI
      shell: bash
      run: |
        gh auth login --with-token <<< "${{ inputs.token }}"
        gh pr create --repo cogup/devops \
          --head ${{ inputs.name }}-update-definition-image-${{ inputs.tag }} \
          --base main \
          --title "Update ${{ inputs.name }} image to ${{ inputs.tag }}" \
          --body "This PR updates the ${{ inputs.name }} image in the cdk-services/definitions/${{ inputs.definition }} file to use the tag `${{ inputs.tag }}`"