name: Image Deploy to GHCR
description: Deploy Docker image to GitHub Packages (GHCR)

inputs:
  repository-name:
    description: Name of the repository (used for the image name)
    required: true
  context:
    description: Path to the context
    required: false
    default: "."
  file:
    description: Path to the Dockerfile
    required: false
    default: "Dockerfile"
  platforms:
    description: Platforms to build for
    required: false
    default: linux/amd64,linux/arm64
  tag:
    description: Image tag
    required: true
  github_token:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ inputs.platforms }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.repository-name }}
        tags: |
          latest
          ${{ inputs.tag }}

    - name: Build and push Docker image to GHCR
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: ${{ inputs.platforms }}
