name: 'k8s deployments Image'
description: 'Update image in k8s repo'
inputs:
  name:
    description: 'Repository name'
    required: true
  tag:
    description: 'Image tag to update in deployment'
    required: true
  token:
    description: 'GitHub token'
    required: true
  deployment:
    description: 'Path to deployment file'
    required: false
  reference:
    description: 'Reference to the deployment file'
    required: false
    default: 'image'

runs:
  using: "composite"
  steps:
    - name: Checkout k8s repo
      uses: actions/checkout@v4
      with:
        repository: cogup/k8s
        ref: main
        token: ${{ inputs.token }}
        path: k8s

    - name: Resolve deployment file
      shell: bash
      run: |
        if [ -n "${{ inputs.deployment }}" ]; then
          echo "path=${{ inputs.deployment }}" >> $GITHUB_ENV
        else
          echo "path=apps/${{ inputs.name }}/deployment.yaml" >> $GITHUB_ENV
        fi

    - name: Modify deployment with new image tag
      shell: bash
      run: |
        sed -i "s|ghcr.io/cogup/${{ inputs.name }}:[a-zA-Z0-9._-]*|ghcr.io/cogup/${{ inputs.name }}:${{ inputs.tag }}|" k8s/${{ env.path }}

    - name: Modify environment variables VERSION
      shell: bash
      run: |
        sed -i "s|\(VERSION:\).*|\1 '${{ inputs.tag }}'|" k8s/${{ env.path }}

    - name: Commit and push changes
      shell: bash
      run: |
        cd k8s
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        BRANCH_NAME="${{ inputs.name }}-${{ inputs.reference }}-update-deployment-image-${{ inputs.tag }}"
        git checkout -b "$BRANCH_NAME"
        git add ${{ env.path }}
        git commit -m "Update ${{ inputs.name }} image with tag ${{ inputs.tag }}"
        git push origin "$BRANCH_NAME"

    - name: Install GitHub CLI
      shell: bash
      run: sudo apt-get install -y gh

    - name: Create Pull Request
      shell: bash
      run: |
        echo "${{ inputs.token }}" | gh auth login --with-token
        gh pr create --repo cogup/k8s \
          --head ${{ inputs.name }}-update-deployment-image-${{ inputs.tag }} \
          --base main \
          --title "Update ${{ inputs.name }} image to ${{ inputs.tag }}" \
          --body "This PR updates the ${{ inputs.name }} image in the ${{ env.path }} file to use the tag `${{ inputs.tag }}`"
