name: Check changes
description: Check changes
inputs:
  path:
    description: 'Path to check'
    required: true
outputs:
  changed:
    description: 'true if changes are detected, false otherwise'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/cogup/actions/check-changes:main'
  args:
    - ${{ inputs.path }}
