name: 'CDK'
description: 'Run CDK'
inputs:
  stack-name:
    description: 'Name of the stack'
    required: true
  context:
    description: 'CDK context'
    required: false
    default: '.'
  ssh-public-key:
    description: 'SSH public key'
    required: false
  ssh-private-key:
    description: 'SSH private key'
    required: false

runs:
  using: "composite"
  steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create id_rsa.pub
        if: ${{ inputs.ssh-public-key }}
        shell: bash
        run: |
          echo "${{ inputs.ssh-public-key }}" > id_rsa.pub
          chmod 400 id_rsa.pub
          ls

      - name: Create id_rsa
        if: ${{ inputs.ssh-private-key }}
        shell: bash
        run: |
          echo "${{ inputs.ssh-private-key }}" > id_rsa
          chmod 600 id_rsa
          ls

      - name: Aws Credentials
        id: aws
        uses: cogup/actions/aws-credentials@main

      - name: Run CDK
        env:
          AWS_ACCOUNT_ID: ${{ steps.aws.outputs.aws-account-id }}
        shell: bash
        run: |
          cd ${{ inputs.context }}
          npm install
          npm run cdk -- synth
          npm run cdk -- deploy ${{ inputs.stack-name }} --require-approval never
