name: Setup
description: Setup monorepo deployment
outputs:
  stage:
    description: 'Status of the stage folder'
  stage-name:
    description: 'Name of the stage'
  stack-name:
    description: 'Name of the stack'
  stack-name-no-stage:
    description: 'Name of the stack without stage'
  lambda-artifacts:
    description: 'Suffix of the lambda-artifacts'
  project-name:
    description: 'Name of the project'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/cogup/actions/setup:main'
