name: Setup
description: Setup monorepo deployment
outputs:
  stage:
    description: 'Status of the stage folder'
  stage-name:
    description: 'Name of the stage'
  stack-name:
    description: 'Name of the stack'
  lambda-artifacts:
    description: 'Suffix of the lambda-artifacts'
  project-name:
    description: 'Name of the project'
runs:
  using: 'docker'
  image: 'Dockerfile'
