name: 'Image Deploy'
description: 'Deploy image to AWS ECR'
inputs:
  repository-name:
    description: 'Name of the repository'
    required: true
  context:
    description: 'Path to the Dockerfile'
    required: true
runs:
  using: "composite"
  steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Aws Credentials
        id: aws
        uses: ./actions/aws-credentials

      # - name: Create ECR repository
      #   uses: ./actions/cdk
      #   with:
      #     stack-name: ${{ env.stack-name }}/${{ env.SERVICE_NAME }}Repository
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ECR
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ steps.aws.outputs.aws-account-id }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
      
      - name: Meta
        id: meta
        shell: bash
        run: |
          echo "prefix=${{ steps.aws.outputs.aws-account-id }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ inputs.repository-name }}" >> $GITHUB_OUTPUT
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          push: true
          provenance: false
          tags: |
            ${{ steps.meta.outputs.prefix }}:${{ env.VERSION }}
            ${{ steps.meta.outputs.prefix }}:${{ env.STAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

